### ISSUE TITLE
V4 Documentation Update Suggestion

### ISSUE THREAD

**Issue by ViolentMinds** [SnailyCAD/docs#1]
### Describe the feature

V4 Documentation Suggestion: 

1) On the Updating Snaily Cad page add a note that says if someone has changed their .env config that they need to run the command for it as well so that they don't forget

2) Add a note that states people need to use a separate SSL certificate for each subdomain for the cad and api and not combine them into one certificate

**Comment by Dev-CasperTheGhost** [comment]
> Add a note that states people need to use a separate SSL certificate for each subdomain for the cad and api and not combine them into one certificate

I don't think this should be listed on the CAD docs 😅.

**Comment by ViolentMinds** [comment]
> > Add a note that states people need to use a separate SSL certificate for each subdomain for the cad and api and not combine them into one certificate
> 
> I don't think this should be listed on the CAD docs 😅.

Its just that major issues I was having installing the CAD was also because of that. I had no idea. Most times you can put multiple domain names into one certificate. All of the Certification programs like Certbot, win-acme allow it. So people might not know. Useful info is never a bad thing to add. You can add an Additional Tips at the bottom of the CAD for Troubleshooting or something
