### ISSUE TITLE
Common error for being redirected to the login screen

### ISSUE THREAD

**Issue by casperiv0** [SnailyCAD/docs#27]
This is quite a common issue which should get more attention in the docs. Most of the time this is due to the following issues:

- Setting `DOMAIN` without using domain for other URLS (`NEXT_PUBLIC_PROD_ORIGIN` or `CORS_ORIGIN_URL`)
- API being offline
- Incorrect DNS settings

**Comment by Dev-CasperTheGhost** [comment]
We could also add a warning on the login page if it has been redirected after 2x
