### ISSUE TITLE
Missing NPM Install docker docs

### ISSUE THREAD

**Issue by DmACKGL** [SnailyCAD/docs#37]
On the Docker docs, there's no mention of running `yarn` for package installation before running `node scripts/copy-env.mjs --client --api`. Because of this, the command fails when trying to import `dotenv`

https://docs.snailycad.org/docs/installations/methods/docker

![image](https://github.com/SnailyCAD/docs/assets/10565361/adde1a2e-f6e4-4b47-b820-a73d2f1655fd)

**Comment by Dev-CasperTheGhost** [comment]
Thanks for reporting, a fix is being deployed now!
