### ISSUE TITLE
Nginx reverse proxy

### ISSUE THREAD

**Issue by burnoutprojects** [SnailyCAD/docs#47]
Can I merge the nginx docs to a single doc page for Windows and Linux installation, because the settings and procedures are almost identical?

**Comment by casperiv0** [comment]
They're not remotely close at all? Why would it be a good idea to merge them?

**Comment by burnoutprojects** [comment]
> They're not remotely close at all?
What do you mean?

The settings is almost identical for Windows and Linux. We can separate with tabs inside the doc for Windows and Linux procedures.  There is no reason to be two separate docs for the different OS. This is my opinion. Other docs is written like this

**Comment by casperiv0** [comment]
Hm, fair enough. Feel free to write it and I'll review it.
